# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/snowy-pub?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:

# Oracle数据库
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: SNOWY-PUB-ORACLE
#    password: 123456

# SQLServer配置
#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=snowy-pub-mssql
#    username: sa
#    password: 123456

# PostgreSQL配置
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/snowy-pub-postgresql
#    username: postgres
#    password: 123456

# 达梦数据库
#spring:
#  datasource:
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://localhost:5236/snowy-pub-dm
#    username: SNOWY
#    password: 123456789
# #达梦数据库兼容问题，不需要在sql语句前加模式名的解决方法：
# #https://blog.csdn.net/myth8860/article/details/100557705

# 人大金仓数据库
#spring:
#  datasource:
#    driver-class-name: com.kingbase8.Driver
#    url: jdbc:kingbase8://localhost:54321/snowy-pub-kingbase
#    username: SYSTEM
#    password: 123456
# #人大金仓数据库兼容问题，不需要加在sql语句中加public的解决方法：
# #在根目录data下的kingbase.conf文档里面找到search_path = '"$user",PUBLIC,sys_catalog'进行替换放开
# #重启数据库即可完全兼容，注意 sql中不能出现mysql中的关键字的单引号
